version: '3.7'
services:
  solr:
    image: solr:9.1.1
    container_name: solr
    hostname: solr
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181
      - SOLR_HEAP=2g
    volumes:
      - ./configs:/configs
      - ./docs:/docs
      - ./lib:/opt/solr/modules/cvlibrary/lib
    networks:
      - solr
    depends_on:
      - zoo

  zoo:
    image: zookeeper:3.6.2
    container_name: zoo
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
      - 7001:7000
    volumes:
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zoo
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - solr

networks:
  solr:
